name: netgeo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python 
  - pyrosm
  - geopandas
  - pandas
  - networkx
  - ipykernel
  - osmnx
#  - libpysal
  - matplotlib  
  - alphashape
  - faker

  - haversine
