name: netgeo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python > 3.6 =< 3.12
  - pyrosm
  - geopandas =<0.14.3
  - pandas =< 2.2.2
  - networkx
  - ipykernel
  - osmnx
#  - libpysal
  - matplotlib  
  - alphashape
  - faker

  - haversine
