name: netgeo_env_tools
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.9
  - geopandas <= 0.14.3
  - pyrosm
  - osmnx
  - pandas <= 2.2.2
  - networkx
  - matplotlib  
  - alphashape
  - faker
  - tqdm