name: netgeo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.9
  - pyrosm
  - osmnx
  - geopandas <= 0.14.3
  - pandas <= 2.2.2
  - networkx
  - ipykernel
  - matplotlib  
  - alphashape
  - faker
  - folium
  - notebook 
  - nb_conda  
  - jupyter_client
  - jupyter_core
  - tqdm